"""abac per-subject resource grants

Revision ID: 010c0bff0b83
Revises: 6919c61ea401
Create Date: 2026-07-13 15:52:12.115904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "010c0bff0b83"
down_revision: Union[str, Sequence[str], None] = "6919c61ea401"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resourcegrant",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_edited", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("tributary_id", sa.Integer(), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column(
            "access_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(user_id IS NOT NULL) <> (tributary_id IS NOT NULL)",
            name="ck_resourcegrant_exactly_one_subject",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["resource.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tributary_id"], ["tributary.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "tributary_id",
            "resource_id",
            "access_type",
            name="uq_resourcegrant_subject_resource_access",
            postgresql_nulls_not_distinct=True,
        ),
    )
    with op.batch_alter_table("resourcegrant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resourcegrant_resource_id"),
            ["resource_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resourcegrant_tributary_id"),
            ["tributary_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resourcegrant_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_column("access_type")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        # access_type moved to ResourceGrant; the original per-resource value
        # is unrecoverable, so backfill with an empty string via a temporary
        # server default, then drop the default to match the pre-rework schema
        # (NOT NULL, no default).
        batch_op.add_column(
            sa.Column(
                "access_type", sa.VARCHAR(), nullable=False, server_default=""
            )
        )
        batch_op.alter_column("access_type", server_default=None)

    with op.batch_alter_table("resourcegrant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resourcegrant_user_id"))
        batch_op.drop_index(batch_op.f("ix_resourcegrant_tributary_id"))
        batch_op.drop_index(batch_op.f("ix_resourcegrant_resource_id"))

    op.drop_table("resourcegrant")
    # ### end Alembic commands ###
