"""add authorization tables (tributary, user_tributary, resource, user_attribute)

Revision ID: 6919c61ea401
Revises: 6001985fea71
Create Date: 2026-06-25 11:10:27.936819

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6919c61ea401'
down_revision: Union[str, Sequence[str], None] = '6001985fea71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tributary',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tributary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tributary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tributary_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_tributary_name'), ['name'], unique=True)

    op.create_table('resource',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tributary_id', sa.Integer(), nullable=True),
    sa.Column('access_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['tributary_id'], ['tributary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_resource_identifier'), ['resource_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_resource_resource_type'), ['resource_type'], unique=False)

    # Add GIN index for JSONB attributes column on resource table
    op.create_index(
        'ix_resource_attributes',
        'resource',
        ['attributes'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'attributes': 'jsonb_path_ops'}
    )

    op.create_table('userattribute',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attribute_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attribute_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'attribute_key', name='uq_userattribute_user_id_attribute_key')
    )
    with op.batch_alter_table('userattribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userattribute_user_id'), ['user_id'], unique=False)

    op.create_table('usertributary',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tributary_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tributary_id'], ['tributary.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tributary_id')
    )
    with op.batch_alter_table('usertributary', schema=None) as batch_op:
        batch_op.create_index('ix_usertributary_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_usertributary_tributary_id', ['tributary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usertributary', schema=None) as batch_op:
        batch_op.drop_index('ix_usertributary_tributary_id')
        batch_op.drop_index('ix_usertributary_user_id')

    op.drop_table('usertributary')
    with op.batch_alter_table('userattribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userattribute_user_id'))

    op.drop_table('userattribute')

    # Drop GIN index on resource attributes
    op.drop_index('ix_resource_attributes', table_name='resource')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_resource_type'))
        batch_op.drop_index(batch_op.f('ix_resource_resource_identifier'))

    op.drop_table('resource')
    with op.batch_alter_table('tributary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tributary_name'))
        batch_op.drop_index(batch_op.f('ix_tributary_code'))

    op.drop_table('tributary')
    # ### end Alembic commands ###
